services:
  database:
    container_name: 23ai
    hostname: 23ai
    image: container-registry.oracle.com/database/free:latest
    environment:
      - ORACLE_PWD=Welcome23ai
      - ENABLE_ARCHIVELOG=false
      - ENABLE_FORCE_LOGGING=false
    ports:
      - "1521:1521"
    # volumes:
    #   - "./oradata/:/opt/oracle/oradata:Z"
    #   - "./sql/startup/:/opt/oracle/scripts/startup"
    restart: always
  ords:
    container_name: ords
    hostname: ords
    image: container-registry.oracle.com/database/ords-developer:latest
    ports:
      - "8181:8181"
      - "27017:27017"
    volumes:
      - "./ords_secrets:/opt/oracle/variables:Z"
      - "./ords_config/:/etc/ords/config/:Z"
    depends_on:
      database:
        condition: service_healthy
    restart: always
  ollama:
    container_name: ollama
    hostname: ollama
    build:
      context: .
      dockerfile: dockerfileollama
    volumes:
      - "./model:/root/.ollama:Z"
    ports:
      - "11434:11434"
    restart: always
  jupyterlab:
    build:
      context: .
      dockerfile: dockerjupyter
    container_name: jupyterlab
    hostname: livelabs
    image: localhost/composescript_jupyterlab
    pull_policy: never
    ports:
      - "8888:8888"
    volumes:
      - "./envvar:/home/oracle/.envvar:Z"
    restart: always
  demo:
    build:
      context: .
      dockerfile: dockerfiledemo
    pull_policy: never
    image: localhost/composescript_demo
    container_name: demo
    hostname: app-server
    volumes:
      - "./app:/app:Z"
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
